### ISSUE TITLE
Missing assignments cannot be edited

### ISSUE THREAD

**Issue by mkazantse** [aopell/SchoologyPlus#101]
If you have a missing assignment (denoted by orange hexagon), you can't modify the assignments grade, and the 3-dot menu to the right doesn't open up.

**Comment by glen3b** [comment]
Addressed in `develop`, largely by stripping the exception and replacing it with the equivalent points-based state when edited.

I believe I've addressed this completely with the following caveats:
- Documentation (which currently states that exception assignments are unsupported) will need an update, presumably in particular to note that assignment will lose their exception state when modified
- There's a stylistic issue when exception state is lost - the edit icon and the grade modified indicator overlap - and I haven't investigated this too much
- I've tried to test this to the extent I can, but given the time of year and the fact that I try to avoid missing assignments, a lot of cases are hard to find test; furthermore, everything with grade editing is precarious

@aopell if you could take a look I would appreciate it

**Comment by aopell** [comment]
I'm experiencing two issues with this that I've seen so far:
1. As you mentioned, the grade edit icon and modified indicator overlap after editing
2. To begin editing, I need to click the edit button twice: the first click removes the exception state from the assignment and the second click actually begins the editing process

**Comment by aopell** [comment]
The HTML differs as follows:

```html
<tr.report-row.item-row>
 <th.title-column>
 <td.grade-column>
  <div.td-content-wrapper>
    <span.awarded-grade>
    <span.max-grade>
    <div.grade-wrapper>
     <img.grade-edit-indicator>
    <br>
    <span.max-grade.injected-assignment-percent>
    <img.modified-score-percent-warning>
 <td.comment-column>
```
for a regular assignment
vs.
for an edited exception assignment
```html
<tr.report-row.item-row>
 <th.title-column>
 <td.grade-column>
  <div.td-content-wrapper>
*   <span.rounded-grade>
    <span.max-grade>
*   <br>
*   <span.max-grade.injected-assignment-percent>
    <div.grade-wrapper>
     <img.grade-edit-indicator>
    <img.modified-score-percent-warning>
 <td.comment-column>
```
