### ISSUE TITLE
Improve Grades link in navbar

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#110]
With the new interface update, Schoology has added the Grades link to the navigation bar because the left sidebar no longer exists. However, there are a few issues with it that I think we should address or at least discuss:

- The Grades button is on the far right side of the navbar links, even though it is the primary reason most people visit Schoology. We previously had it on the very left and I think it belongs there.
- When the window size becomes too small horizontally, the grades button and the calendar button turn into a "More" menu, requiring an extra click to access
- The grades button is not actually a button, but in fact a dropdown containing Grade Report and Mastery. I'm not sure how common Mastery is, but I feel like the Grade Report should be much easier to access.

**Comment by glen3b** [comment]
I've implemented my suggestion above.
@aopell thoughts?

**Comment by glen3b** [comment]
Potential alternative in low-width case:
Instead of removing "Grades" for "More..." remove "Resources." Make "Grades" a direct link in the root menu, and "More..." can have Resources, Mastery, and Calendar.
