### ISSUE TITLE
Add LAUSD blue theme

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#112]
With LAUSD's new Schoology UI update, they have a new theme, "LAUSD Blue" (a dark blue which is, in my opinion, much nicer than the old LAUSD orange). We should add it as an option for Schoology Plus users.

Also worth discussing: with the new UI, do we want to make any changes to our default theme preferences?

**Comment by aopell** [comment]
Closed in f6a2a4bfd4431ef0d2566de033470362c02d8a5f
