### ISSUE TITLE
Add a notice that the page will reload when unchecking "Enable grade modification"

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#119]
It's currently not obvious this will happen, and people might assume they can toggle between modified grades and original grades with the check box

**Comment by glen3b** [comment]
What form should this take? We could prompt with one of the browser built-in prompts upon toggle; alternatively, we could add a warning exclamation mark or something. I like the intrusive prompt after click - it has the added bonus of not needing new UI elements.

**Comment by aopell** [comment]
Yeah I was thinking a built in browser prompt
