### ISSUE TITLE
Add a sidebar to the home page that lists all courses for easy one-click access

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#120]
Numerous survey respondents stated they would like to be able to more quickly jump to the grades or assignments page for a course. A few mentioned that a good way to do this would be to create a sidebar on the left of the home page which lists courses for one-click access. Survey results in general show that people are unhappy with the number of clicks it takes to reach grades.

**Comment by glen3b** [comment]
Are the survey responses regarding accessibility of grades from the old or new UI? There were significant, relevant changes with that update.

**Comment by aopell** [comment]
They were from the old UI, however there might still be some improvements we can make.
