### ISSUE TITLE
Add default course icons for more courses

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#122]
Survey responses indicate this is desired, however without a list of specific classes this is difficult. We could potentially organize some way of asking users which courses don't have icons.

**Comment by glen3b** [comment]
Without a list of courses this is exceedingly difficult. Does LAUSD provide a list of courses somewhere? I think they might. The UC system I believe also tracks courses offered by individual schools, and makes that registry available publicly, but I don't know if it has transcript abbreviations.

**Comment by glen3b** [comment]
LAUSD course catalog: https://coursecatalog.lausd.net/CourseCatalog/
UC course catalog: https://hs-articulation.ucop.edu/agcourselist

**Comment by aopell** [comment]
I thought about this a little, and maybe we should scan for peoples' courses without icons and then notify them and ask if they would like to anonymously send us a list of classes to add icons for. Just a thought.
