### ISSUE TITLE
Add indication of number of points needed to reach each grade

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#123]
A couple survey respondents noted they would like to be able to see how many points they need to reach the next grade and the buffer of points they have until they fall to a lower grade. This is possible for unweighted classes only.

**Comment by aopell** [comment]
I believe at least one survey respondent suggested this be implemented as mouseover text, which might be a good idea.

**Comment by glen3b** [comment]
What would this be logically?
For a fixed denominator, a point value can be computed where if that many points had been obtained with the existing denominator, the grade would be (e.g.) an A. This is what I intuitively think of when I hear "points needed for a grade," but practically I don't know how useful it is. The other conception I have is finding what worth _n_ a new assignment would need, with a 100% score, to bring the grade to a given average. This is less intuitive on many but arguably more useful.

If I were to implement this today I would take the former approach, but the ambiguity in the phrase "points needed" (which limits its utility) bothers me. Any thoughts @aopell?

**Comment by aopell** [comment]
That is a fair point, and this does seem somewhat strange. However I would say the potentially useful situation for the former is knowing how many extra credit points/points you would need to bribe your teacher for to get the next grade.
