### ISSUE TITLE
Schoology Plus interferes with quiz submission in Firefox

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#137]
Submitting quizzes on Schoology with Schoology Plus enabled has the following behavior:
- Submit is clicked: it opens the confirmation modal - expected behavior
  - The "No" button is thematically incorrect in BOTH Chrome and FIrefox
- The "Yes" button does nothing - it should submit the quiz (this is only observed in Firefox)
- After clicking "Yes" and closing the modal (e.g. through "No" or the "X" button), clicking "Submit" directly submits the quiz without another confirmation prompt

There are two issues here:
- "No" is thematically incorrect in all browsers
- "Yes' doesn't submit in Firefox

**Comment by glen3b** [comment]
I get this error in Firefox when I click "Yes."
![The error that appears](https://i.imgur.com/x0rtHn7.png)

I feel like we've seen the `Permission denied to access property "apply"` error before in Schoology code. As I recall we didn't find the root cause and had to implement a workaround. Any insights @aopell? I think you dealt with this last time.

**Comment by aopell** [comment]
I don't recall that error specifically but it could be similar to the arrow drop down not working previously in Firefox. To be clear, you can submit quizzes in Chrome even with Schoology Plus installed?

**Comment by glen3b** [comment]
Correct, with Schoology Plus in Chrome there is no issue submitting quizzes like there is in Firefox.

**Comment by glen3b** [comment]
And yes, it's the arrow issue I was thinking of. I'm pretty sure we got a similar error in similar circumstances in Firefox only.
