### ISSUE TITLE
Layout issue in grades page with short comments

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#138]
User reported bug. Occurs both with and without grade editing enabled. Screenshots from Chrome. This was in a class with many small categories. Another assignment with a longer comment did not appear to have this issue.

![image](https://user-images.githubusercontent.com/3952667/53217745-2897f480-360e-11e9-9a8a-ab9ee604fe54.png)
![image](https://user-images.githubusercontent.com/3952667/53217757-2fbf0280-360e-11e9-881a-69fbc36e0497.png)

**Comment by aopell** [comment]
Is the issue that the comment is aligned left instead of right?

**Comment by glen3b** [comment]
Yes. The three dots (and the comment) are not right-aligned, like they are in every other row.
