### ISSUE TITLE
Accept and cancel action buttons are inconsistently styled between dialog boxes

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#139]
This was mentioned as part of #137, but it's a separate bug.

Based on initial investigation, it's not directly caused by Schoology Plus CSS (although it's quite possible I'm missing something), which is strange.

**Comment by glen3b** [comment]
Here's a vanilla Schoology screenshot:
![splusconfirmsubmit](https://user-images.githubusercontent.com/3952667/53427536-f84dae80-399d-11e9-9276-bb14c3226e1f.png)

It appears we reskin the background but not the foreground. For now I'm going to reskin the foreground color as white.

@aopell you might want to take a look at this. The potential issues I can foresee are if we want a dark foreground (e.g. light background) in themes for whatever reason and we need to centralize foreground color logic, or if we want to keep Schoology's stylistic distinction between Yes and No, which we currently aren't doing.

**Comment by glen3b** [comment]
The rationale for my changes is to make the buttons stylistically similar in light of the fact that Schoology Plus makes their backgrounds the same - any discrepancy is weird.

That said from a design perspective if we want to change this behavior to preserve Schoology's original difference between affirmation and cancellation actions, that would necessitate a different approach to this issue. I'm not closing this yet because I'd still like @aopell to take a look at this with an eye to Schoology Plus design decisions.

**Comment by aopell** [comment]
Ok this seems to be another one of Schoology's many unexplainable inconsistencies:

Currently (with your fix in place) Schoology quiz submission modals appear like this: 

![quiz sumission](https://user-images.githubusercontent.com/5026980/54261269-9b6b0000-4528-11e9-9295-d359d1df6313.png)

Other modals with a clear confirm/accept action (such as the add file modal in resources as well as pretty much every other modal I can find) appear like this:

![other modals](https://user-images.githubusercontent.com/5026980/54261387-ea189a00-4528-11e9-9e01-826b712363f2.png)

The reason for this that I can see is that most modals (the latter) put their buttons in a `div` with the class `submit-buttons` while the quiz submission modal uses the class `popups-buttons`. We should probably pick one style that we like (either the latter from above or a completely new style) for all modals and use that consistently.

**Comment by aopell** [comment]
I'm also going to tack two more problems onto this issue:

1. When "reviewing answers" on a quiz, the "Return to Page 1" button is styled incorrectly
2. When submitting a quiz from the "reviewing answers" stage, both the "submit" and "back" buttons are styled identically. We should style "back" the same way we decide to style other types of cancellation buttons.

**Comment by glen3b** [comment]
I thought I had fixed the dark-text-on-dark-background issue. This is in Firefox:
![SubmitAssessmentPrompt](https://user-images.githubusercontent.com/3952667/54291230-819ddd00-4569-11e9-9c28-92353cb01078.png)

Interesting (and annoying) that Schoology is stylistically inconsistent here. Logically I think it makes more sense to mark quiz submission confirmation as `submit-buttons`, as that (I would think) more logically implies a cancellation-affirmation dichotomy than a generic `popup-buttons` class. I don't remember how they selected it, but they have a distinct CSS selector for cancellation buttons under `popup-buttons`. Regardless, yes, that's something to look at.
