### ISSUE TITLE
Lock popups from scrolling

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#141]
Currently, Schoology popups don't handle scrolling; they're just on the page. This means you can scroll past them onto a white background.

In other words, Schoology default popups won't stay in the same place on the viewport if spawned on a page which scrolls, so you can scroll away from popups.

Based on how i'm interpreting their features list, Boostogy fixes that; regardless of if they do or not, it's a good idea for something for us to improve.

**Comment by aopell** [comment]
Copying the commit message from 1dd84e4 here:

```
Previously old-style default Schoology popups would stay in a fixed position on the page. That behavior has been modified to prevent the user from scrolling the page. In addition, when the page is resized horizontally, the popup window is now re-centered (previously it did not move).

In addition, previously Schoology Plus modals would allow the background page to be scrolled while they were opened. This is no longer possible.
```
