### ISSUE TITLE
Chrome web store listing needs improvements

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#142]
The images and description on the web store need updating, and in addition to that we don't have many reviews at all. Thoughts on prompting users to review the extension on the web store with the next update via popup and news feed post @glen3b?

**Comment by glen3b** [comment]
I'm hesitant to be intrusive for marketing purposes, but our popups aren't that bad. Certainly a news feed post would be OK. I don't think in this context an announcement would be inappropriate on grounds of excessive frequency, but in general I'd like to be very careful not to bombard our users with enough requests to "rate and review" on the webstore to cause our users to ignore either those popups or our popups in general.

**Comment by aopell** [comment]
Yeah we certainly won't do this often, but I don't really see a problem with doing it once.
