### ISSUE TITLE
All cross origin requests (i.e. Schoology API calls) must be moved to background page

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#144]
As of yesterday (3/12/19) Google Chrome version 73 was released to the stable branch which brings changes to cross origin requests. Notably, by default all cross-origin requests that appear to contain JSON or HTML that have MIME types that don't match are automatically blocked by a new security feature CORB (Cross-Origin Read Blocking).

According to [this Chromium support page](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches):
> tl;dr: To improve security, cross-origin fetches will soon be disallowed from content scripts in Chrome Extensions.  Such requests can be made from extension background pages instead, and relayed to content scripts when needed.

So therefore we must move all of our Schoology API calls and other cross-origin requests (if there are any?) to the background page and then send the data to the foreground scripts.

**Comment by aopell** [comment]
Example: 
![Example](https://user-images.githubusercontent.com/5026980/54260850-5befe400-4527-11e9-8c59-88a4dcb82a31.png)

**Comment by glen3b** [comment]
Annoying, but we abstract Schoology API calls to a Promise based wrapper anyway, so shouldn't be too bad.

Are we expecting any necessitated behavioral changes? Will our fix for Chrome have negative effects in Firefox?

**Comment by aopell** [comment]
I don't assume this will have negative effects in Firefox, and it does seem fairly straightforward. We may want to move this to an even sooner release as some functionality (though not the most important) will be broken until this is addressed.
