### ISSUE TITLE
Quizzes: Show popup when attempting to submit a quiz with unanswered questions

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#145]
Personally I feel Schoology doesn't do a good enough job of alerting you that you haven't answered a question yet.

This is all you get:

![non-answered question](https://user-images.githubusercontent.com/5026980/54261719-b5f1a900-4529-11e9-8576-7bfef6423dce.png)

Seems easy to miss on a long quiz page if you're scrolling a bit too quick.

**Comment by glen3b** [comment]
We could add it to the submission confirmation dialog:
"Are you sure you want to submit?
You have 1 unanswered question."
