### ISSUE TITLE
Re-enable automatic missing icon detection

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#161]
After adding many icons, there should be few people receiving this prompt again anyways.

**Comment by glen3b** [comment]
Should we change the structure of this so it's periodic, or is triggered by changes in course roster, instead of being a once-off we have to alter?

**Comment by aopell** [comment]
Yeah, we probably should. What's a fair period for this? Monthly?

**Comment by glen3b** [comment]
Every semester seems sensible to me; every 6 months?
