### ISSUE TITLE
Grade editing crashes when editing the sole gradeless assignment in a class

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#19]
If a class has one assignment with no grade (and the course has no grade), the editor crashes after applying changes to category grade but before changing the course (period) grade.

[Screenshots](https://imgur.com/a/yntPm)

**Comment by glen3b** [comment]
Can this still be reproduced on the latest version?

**Comment by aopell** [comment]
This issue has been stale for 7 months now, is there any easy way to test this? Does this apply to version 4.1/4.2dev?

**Comment by glen3b** [comment]
If I recall correctly it has to do with the fact that there's no computed total point value for the class/that there's no denominator or numerator to read. Since we haven't touched that particular code, it's probably still an issue; that said, there's not a great way to test without a test course.
