### ISSUE TITLE
Add support for other Schoology instances

### ISSUE THREAD

**Issue by KleinKravis** [aopell/SchoologyPlus#225]
**Describe the bug**
Schoology Plus only works on schoology.com

**To Reproduce**
Go to a Schoology page other then schoology.com (eg schoology.spps.org)
No features

**Additional context**
Add support for more domains

**Comment by glen3b** [comment]
Hello! It looks like we're already tracking this at #88; if you could add anything additional in that ticket we'd appreciate it. I'm going to close this as a duplicate; if you believe this to be in error, please comment why.
