### ISSUE TITLE
Background Page Fetch Doesn't Work on Firefox >79

### ISSUE THREAD

**Issue by Arsen6331** [aopell/SchoologyPlus#234]
**Describe the bug**
`backgroundPageFetch()` in /js/preload.js is returning an error and when `processNonenteredAssignments()` in /js/grades.js attempts to use the `in` operator, an error occurs

**To Reproduce**
Attempt to enable what-if grades on Firefox 84

**Expected behavior**
What-if grades turns on and works without issue

**Additional context**
Attempting to rebuild extension without `in` operator resulted in `Response is undefined or null. Last error: Error: Could not establish connection. Receiving end does not exist.`

**Comment by aopell** [comment]
Hi! Thanks for filing this issue.

We're currently aware of a number of problems relating to making Schoology API calls in Firefox (it appears to be a browser bug as everything worked up until Firefox 79).

We don't have an open ticket for that issue though, so I'm going to convert this ticket to be the more general problem.

Thanks!

**Comment by aopell** [comment]
Root cause of this issue is undetermined; it's either a browser bug (as the extension works fine on Firefox 78) or an undocumented change to the WebExtensions API. More investigation is needed.

**Comment by aopell** [comment]
Related:

https://bugzilla.mozilla.org/show_bug.cgi?id=1657384
