### ISSUE TITLE
Beta: Random thing on right

### ISSUE THREAD

**Issue by KTibow** [aopell/SchoologyPlus#239]
**Describe the bug**
On the course page, underneath the "Upcoming" section, there's a random thing on the right:
![image](https://user-images.githubusercontent.com/10727862/103799533-10fa6700-5000-11eb-8103-9d6e8a3bb404.png)
This is actually a preloaded React document viewer iframe:
![image](https://user-images.githubusercontent.com/10727862/103799629-325b5300-5000-11eb-83da-c05ca7214921.png)

**To Reproduce**
1. Go to the course page.
2. Look on the right.
3. See bug.

**Expected behavior**
It not to be there because it would be excluded by something like
```css
#right-column-inner > div[id^=sgyReactRenders_comp_] {
  display: none;
}
```
**Screenshots**
![image](https://user-images.githubusercontent.com/10727862/103799802-6fbfe080-5000-11eb-832f-3ddf46497334.png)

**Additional context**
Using `darktheme` beta.

Info: Edge 87.0.664.66, with Windows build 19042, at https://nsd.schoology.com/, 6.7.1

**Comment by aopell** [comment]
Yeah... we're aware of that one. I wasn't sure if we should be in the business of hiding things that don't currently show something, but either might in the future or do on certain Schoology instances but not others.

Can we be completely sure that nothing ever shows there? And if so can we be sure of it entirely using CSS? I'm doubtful.

**Comment by aopell** [comment]
According to a member of our Discord server:

> i believe the "random thing on the right" in issue #239 is for events scheduled by the school itself, such as holidays
> **Julian#6749** | Schoology Plus #contributions | Message ID 796464242986975242

**Comment by KTibow** [comment]
Odd. From my inspections it looks like it's just preloading the document viewer, but I'm not sure.

**Comment by aopell** [comment]
Yeah, that's what it appears to be. I'll take a look at it, but if we're fairly confident it's *always* supposed to be hidden we can hide it.
