### ISSUE TITLE
Grade loading hangs (fails) if localStorage API key invalid

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#24]
Grade loading in courses with missing assignments fails and hangs if the API credentials in localStorage are invalid, for instance if the key has been regenerated.

**Comment by glen3b** [comment]
I do like the auto API key management for end-user experience, it's a clever way to enable access to a more elegant solution for programming against Schoology.

Thoughts on this issue:
- Requery API key page every load
I don't like this because that's an extra HTTP request per grade page load and seems overkill, but on the other hand it's only one request and bypasses localStorage and its associated cache invalidation problem entirely.
- Passively requery API key on load failure (as in, do not regenerate the key if it is not present)
I think this is the best option. Resolves this particular issue but doesn't risk ruining other potential user API uses. On the other hand, this necessitates secondary error handling and awaiting another call; if this isn't the issue behind a query failure, it's a wasted call and we're stuck in the LOADING situation with uncertain total grade.
Perhaps if the reload fails (after the initial request fails, we try to refresh and fail), purge the localStorage cache and try again later? In either case, there's an open issue of what to do when loading fails.
- Regenerate API key on load failure
If the user uses the API anywhere else, this will constantly break their app - I don't like this idea. Doesn't solve much more than the passive option.

In terms of error-handling, potentially just disable grade editing on that category and/or assignment (depending on if course is weighted or not) instead of nuking the grade display which Schoology has *already calculated*? The grade *is* known, it only becomes an issue if editing is employed; adding a grade display (instead of LOADING) without editing (i.e. actively disable editing) is more useful than displaying LOADING and breaking editing.

**Comment by aopell** [comment]
> In terms of error-handling, potentially just disable grade editing on that category and/or assignment (depending on if course is weighted or not) instead of nuking the grade display which Schoology has already calculated? The grade is known, it only becomes an issue if editing is employed; adding a grade display (instead of LOADING) without editing (i.e. actively disable editing) is more useful than displaying LOADING and breaking editing.

Yeah I totally hear you and I agree, that's probably a better solution.

> Requery API key page every load

This is probably the solution to go for

**Comment by glen3b** [comment]
In that case we can ditch the localStorage cache.

Regarding grade edit toggling, I'm realizing the drawback is that displayed denominators would be inaccurate (percentages would be fine, but not point totals). To fix this, potentially some algebra (pointsEarned / percentEarned = pointsTotal) to calculate the denominator - unsure of how that will work given floating point imprecision.

**Comment by aopell** [comment]
Moved remainder of this discussion to #26
