### ISSUE TITLE
Default icon set not applying

### ISSUE THREAD

**Issue by KTibow** [aopell/SchoologyPlus#240]
**Describe the bug**
The custom icon set's default icons aren't applying, however they work just fine in the default icon set preview when I paste my course's name.

**To Reproduce**
1. Apply theme Schoology Plus
2. Go home and look at courses
3. See not applying

**Expected behavior**
The icons to change.

**Screenshots**
![image](https://user-images.githubusercontent.com/10727862/103801882-30df5a00-5003-11eb-98d0-0ee8d4c66195.png)
(Personal details removed for privacy)
![image](https://user-images.githubusercontent.com/10727862/103802052-6f751480-5003-11eb-8ddd-1ead6a9b447e.png)

**Additional context**
Custom icons in the theme work fine. I'm available to do troubleshooting.

Info: Edge 87.0.664.66, with Windows build 19042, at https://nsd.schoology.com/, 6.7.1

**Comment by aopell** [comment]
This is actually an intended feature. The custom icons are designed specifically to work with course names from the Los Angeles Unified School District, and to prevent incorrect icons applying we disabled the default icon set unless you're using the LAUSD Schoology page. We can discuss adding an option to use it even when you aren't in LAUSD, but there would be no support for us fixing icons that show up incorrectly.

**Comment by KTibow** [comment]
Maybe the docs could be updated, or there could be a dropdown to choose from in the icon chooser? Or you could just add only stuff that makes sense to be globally applied.

**Comment by glen3b** [comment]
I like the idea of making the default icon set easier to find.

**Comment by aopell** [comment]
I think the right approach here is probably a new setting "Use Default Icon Set" which defaults to `true` for the LAUSD instance and `false` otherwise.

I'll add this to the roadmap.

**Comment by aopell** [comment]
Fixed for next version
