### ISSUE TITLE
Schoology Plus doesn't activate on custom URLs

### ISSUE THREAD

**Issue by ROTARTSI82** [aopell/SchoologyPlus#251]
### Describe the bug

Schoology plus doesn't activate on custom schoology URLs (e.g. `https://schoology.harker.org`)

### Steps to reproduce

1. Install schoology plus and go to a custom url

### Expected behavior

Schoology plus activates and works.

### Screenshots

None

### Additional context
none

### Platform

Any platform, both latest chrome/firefox. on schoology.harker.org

**Comment by aopell** [comment]
For anyone discovering this issue later, until we have a better solution for this the workaround is available here: https://github.com/aopell/SchoologyPlus/pull/252#issuecomment-772741882
