### ISSUE TITLE
What-if Grades Semester Grades Issue

### ISSUE THREAD

**Issue by thavens** [aopell/SchoologyPlus#255]
### Describe the bug
Bug causing second-semester what-if grades to be applied to the first semester.

### Steps to reproduce
Separate grades into 2 semesters then use what-if grades on a grade item in the second semester causes the first semester overall grade to change while leaving the second semester grade unchanged.

### Expected behavior
Using what-if grades in the second semester causes what-if grades to perform the math on the second semester's grade.

### Screenshots
![image](https://user-images.githubusercontent.com/67104840/109785284-d6a4e480-7bc0-11eb-98dc-5105918eb3e9.png)
![image](https://user-images.githubusercontent.com/67104840/109785439-fb995780-7bc0-11eb-8fa4-1d012c2f56ee.png)

### Additional context
As you can see above I've added a large amount of score to the second-semester homework category but rather than affecting '20-21 T2' section's grade it updates '20-21 T1' section's grade.
'20-21 T1' and '20-21 T2' correspond to the first and second semesters respectively.

### Platform
> browser name, browser version, and Schoology Plus version
Chrome, Version 88, Schoology 7.1

**Comment by aopell** [comment]
Hello! thanks for your report! this has been fixed in v7.2 which was just released and should be available on Chrome within the next few days!
