### ISSUE TITLE
Assignment checklist doesn't work with assignments without submissions

### ISSUE THREAD

**Issue by r2dev2** [aopell/SchoologyPlus#257]
### Describe the bug
> When an assignment that does not use submissions is manually marked as completed, it causes all other non-submission assignments to also be marked.

### Steps to reproduce

https://user-images.githubusercontent.com/50760816/111058335-c8698a80-8442-11eb-8544-40ffcba689be.mp4

### Expected behavior
> The other assignments should not get checked

### Screenshots
> See video

### Additional context
> n/a

### Platform
> Firefox 86.0, fuhsd.schoology.com, Schoology Plus v7.2

**Comment by aopell** [comment]
I believe this should be fixed in the next version
