### ISSUE TITLE
Better handle failures in API calls

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#26]
> In terms of error-handling, potentially just disable grade editing on that category and/or assignment (depending on if course is weighted or not) instead of nuking the grade display which Schoology has already calculated? The grade is known, it only becomes an issue if editing is employed; adding a grade display (instead of LOADING) without editing (i.e. actively disable editing) is more useful than displaying LOADING and breaking editing.

Created from a [comment](https://github.com/aopell/SchoologyPlus/issues/24#issuecomment-387596228) by @glen3b on #24 

This may not be an issue anymore after switching to API retrieval of assignment max points

**Comment by glen3b** [comment]
I've just done some testing on the related topic of errors thrown in async functions - good news, they properly show up as uncaught.

I suspect the original case in which this showed up occurred most often with an invalid API key state - resolved in #38 - but the underlying issue remains.

Hopefully this can be resolved as part of #44.
