### ISSUE TITLE
Change of course title doesn't do anything.

### ISSUE THREAD

**Issue by masiv1001** [aopell/SchoologyPlus#267]
Describe the bug
If you give a nickname to a course, it doesn't change anywhere.

To Reproduce

    Give a course a nickname
    Look anywhere the course title appears
    See no change 

Expected behavior
Course title to change

Screenshots
![2021-10-06 00_08_04-Calificaciones _ Schoology — LibreWolf](https://user-images.githubusercontent.com/79378620/136134656-7f0ffc2a-6310-4fe5-92fe-e396c15f7988.png)
![2021-10-06 00_07_53-Calificaciones _ Schoology — LibreWolf](https://user-images.githubusercontent.com/79378620/136134652-843a72dc-d90e-43f5-bec9-87b63f3ad9bb.png)

Additional context
Firefox browser

**Comment by jetline0** [comment]
Upon further observation, I think it's an issue with the auto generated theme rather than a browser issue.
All the default themes work (with the exception of not changing the name in the Courses tab).

**Comment by jetline0** [comment]
Okay - for me the fix was disabling other Firefox extensions until the problem was fixed. Sorry for bumping this 3 times, but I've managed to resolve it on my end by disabling a light/dark mode extension.
