### ISSUE TITLE
Text on "Grades" dropdown is unreadable on any theme.

### ISSUE THREAD

**Issue by ScanuNicco** [aopell/SchoologyPlus#272]
### Describe the bug
The text and background on the "Grades" dropdown are colored white regardless of the theme, making the text unreadable.

### Steps to reproduce
Click the grades button to open the dropdown.

Note that the dropdown only appears if your school has enabled the Mastery page.

### Expected behavior
The dropdown follows the background and text colors of the theme, and text is readable.

### Screenshots
![Image of the bug](https://user-images.githubusercontent.com/30136040/146474240-f9a822fa-ae9f-48f8-99f9-f014500ede81.png)
**The background remains white instead of following the dark theme**

![image of the bug](https://user-images.githubusercontent.com/30136040/146474575-5627676e-e662-4b27-981c-a61a4bdc2898.png)
**The text remains white instead of following the light theme**

![image of the dropdown working correctly](https://user-images.githubusercontent.com/30136040/146474856-d0b158f9-2114-4fc1-83ec-3eb926086dd0.png)
**The text is readable when the Schoology Plus extension is disabled**

### Additional context
The dropdown only appears when schools have the "Mastery" page enabled, so most people will probably never see it.

### Platform
Browser: Microsoft Edge 95 (Beta)
Schoology URL: https://app.schoology.com/
Schoology Plus Version: 7.3.5

**Comment by sethpeace** [comment]
I'm having the same issue in Opera GX

**Comment by colenh** [comment]
any updates?

**Comment by aopell** [comment]
I can't reproduce this myself, is there any way you can find which CSS class I might need to override in order to set the background color correctly? This is what we're currently using
![image](https://user-images.githubusercontent.com/5026980/156680196-e4522dbc-5931-4bf5-953d-39760c6499b0.png)

**Comment by sethpeace** [comment]
![image_2022-03-03_195303](https://user-images.githubusercontent.com/14851383/156696215-dc62cce7-3e9c-49ff-9e25-e803587fa567.png)
