### ISSUE TITLE
Firefox Addon won't install

### ISSUE THREAD

**Issue by AkshatAdsule** [aopell/SchoologyPlus#274]
### Describe the bug
Firefox Addon won't install due to it being unverified

### Steps to reproduce
Visit Schoology+ website
Go to downloads section
Click on firefox

### Expected behavior
Should install add-on, currently does not

### Screenshots
<img width="475" alt="image" src="https://user-images.githubusercontent.com/30205531/151903531-454110e9-fd13-437e-839b-3e342efcfd05.png">

### Additional context
Not sure how the addon is built, but fixing it could be as simple as running the sign command with the web-ext command. More info [here](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-sign).

### Platform
Firefox 96.0.3 (64-bit)

**Comment by jschenke488** [comment]
Use Firefox Nightly or Developer Edition. Mozilla removed the add-on and is taking a long time to approve it again.

**Comment by TheBlueOompaLoompa** [comment]
I'm using firefox developer edition and it still gives that error message.

**Comment by TheBlueOompaLoompa** [comment]
Nvm found the solution [https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users)

**Comment by zoey-on-github** [comment]
Shouldn't this issue be closed, since a solution was found?

**Comment by aopell** [comment]
I'm working with Mozilla currently to figure out why they won't sign our addon files, stay tuned.
