### ISSUE TITLE
Quick Access not appearing for me

### ISSUE THREAD

**Issue by zoey-on-github** [aopell/SchoologyPlus#278]
I've tried this on multiple devices on several browsers(brave and librewolf on windows, chrome on chromeos) I have the option selected to show it selected, as you can see here: 
![image](https://user-images.githubusercontent.com/88806187/156633151-8cb0e0d0-2bf8-4bdb-94f1-edb1a53affd8.png), but it doesn't apppear: 
![image](https://user-images.githubusercontent.com/88806187/156633685-5aeab3ce-b654-4e77-b99d-e2e9b8da98c0.png)

Reinstalling the extension doesn't help, and disabling my other extensions did nothing.

**Comment by zoey-on-github** [comment]
I should note that this doesn't just appear to be a "me" issue as it doesn't seem to appear on any of my friends' pcs either

**Comment by aopell** [comment]
This has been fixed by the latest release. It is available now for Chrome and will be available soon for Edge.

**Comment by aopell** [comment]
Quick update, yet another new version was published that will show up soon, so if you're experiencing this again it should be resolved soon.
