### ISSUE TITLE
"My Courses" and "Past Courses" links do not work with Link Color when styling

### ISSUE THREAD

**Issue by Lolol4572** [aopell/SchoologyPlus#294]
### Describe the bug
Whenever I set the color for links to be dark, I notice that the "my Courses" text and "Past Courses" text does not follow the dark color when styling, even though they are links. 
### Steps to reproduce
> Detailed steps to reproduce the behavior you describe
Whenever I set the color for links to be dark, I notice that the "my Courses" text and "Past Courses" text that shows up on the Courses dropdown menu does not follow the dark color when styling, even though they are links. The background is normally a light color, so they are hard to see.
### Expected behavior
> A clear and concise description of what you expected to happen.
I expected that they would follow the dark link color, which would make it easier to see.
### Screenshots
> If applicable, add screenshots to help explain your problem.
![Screen Shot 2022-11-13 at 5 49 13 PM](https://user-images.githubusercontent.com/87130878/201549028-5bb65045-5314-42cb-9852-34223627be5c.png)

### Additional context
> Add any other context about the problem here.

### Platform
> Please include your browser name, browser version, Schoology URL (if you feel comfortable), and Schoology Plus version
Chrome 107.0.5304.107 Schoology Plus v7.5

**Comment by Roguim** [comment]
Looks like that and the footer links are set to the contrast text colour. Thanks for letting us know!
![image](https://user-images.githubusercontent.com/39052241/201561251-09486b8a-bd42-4b82-a1d6-4bcf3b82fe3c.png)
