### ISSUE TITLE
API key blocked by schoology plus

### ISSUE THREAD

**Issue by alexmehta** [aopell/SchoologyPlus#295]
### Describe the bug
> A clear and concise description of what the bug is.
Schoology Plus takes over API key page.
### Steps to reproduce
> Detailed steps to reproduce the behavior you describe
go to https://[schoology_domain]/api
you will be met with the page requesting access to API keys. After accepting and going back to the same API page, you cannot yourself access your own API key because of schoology plus menu. 
### Expected behavior
> A clear and concise description of what you expected to happen.
After declining, users should be sent to the original API key page. After accepting, the schoology API page shouldn't still replace the original one. 
### Platform
> Please include your browser name, browser version, Schoology URL (if you feel comfortable), and Schoology Plus version
Firefox 107 on linux mint. Schoology Plus 7.5.

**Comment by Roguim** [comment]
![image](https://user-images.githubusercontent.com/39052241/202584201-266d50fe-0d06-40b7-8a6c-5c2b9d35eb4a.png)
Would this kind of thing solve it-- an X button in the top corner of the box to go back to the normal schoology api page?

**Comment by alexmehta** [comment]
I think that would solve the issue. As long as I can access the actual API page.

**Comment by Roguim** [comment]
Alright, it's solved in #290 then, just waiting on it to be merged in.

**Comment by alexmehta** [comment]
Thanks! Will close issue.
