### ISSUE TITLE
Customizable color

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#3]

**Comment by glen3b** [comment]
I've briefly experimented with a toggleable preference for theme injection backed by local storage in my fork and it appeared to introduce substantial (as in noticeable, compared to unnoticeable for current CSS injection) latency - I'm not sure why this is, perhaps an implementation flaw on my part. FF 57 Linux.

**Comment by glen3b** [comment]
[Green theme CSS](https://github.com/glen3b/SchoologyPlusPlus/blob/master/css/all.css), as an alternative.
