### ISSUE TITLE
Incorrectly Sized "Timer" Icon on Homepage

### ISSUE THREAD

**Issue by Jiaming-S** [aopell/SchoologyPlus#304]
### Describe the bug
> A visual bug with the new Schoology appearance where the "timer" icon (which appears when an assignment is due within 24 hours) is wrongly sized. 

### Steps to reproduce
> Open Schoology's home page. Whenever a checkbox appears for an assignment that has the "timer" icon, the icon will become incorrectly sized. 

### Expected behavior
> Timer icon should be smaller and sized consistently for every assignment

### Screenshots
> <img width="450" alt="schoology_plus_incorrect_size" src="https://user-images.githubusercontent.com/112342179/229899089-dc4b95ba-4abd-4c57-b13a-94f447c3f32b.png">

### Platform
> Firefox 111.0.1 (64-bit)
> MacOS Monterey
> Schoology Plus Version 7.7.3

**Comment by dzlandis** [comment]
This also applies to the overdue icon as well.
![nkQon31VLL](https://user-images.githubusercontent.com/49926644/229922396-ba013a0e-5307-4951-802a-f9355c5ddb1d.png)
