### ISSUE TITLE
Post input box not affected by theme

### ISSUE THREAD

**Issue by TheThonos** [aopell/SchoologyPlus#312]
### Describe the bug
The text box where you can write a post in a group does not change colors based on the theme, resulting in a big contrast if you have a dark theme.

### Steps to reproduce
Apply a theme and go to a Schoology group and look at the input box for posting.
I have tested this with this theme: {"color":{"custom":{"background":"#36393f","border":"#40444b","hover":"#40444b","link":"#6fa8dc","primary":"#202225"},"modern":{"calendar":["#457da5","#547c41","#926c37","#7c3d6b","#0b4c9c","#00209c","#004a09","#72721a","#44233e","#683131","#770a0a","#a72413","#e0024c","#188c16","#bd7304","#80168c","#164152","#00543f","#633e11","#461b2d","#00427c","#603073","#8b1941","#970c0c","#9c3b07","#685203","#2a5f16","#09584f","#005a75","#4d5557"],"dark":true,"interface":{"accent":"#2f3136","active":"rgba(0, 255, 255, 0.1)","border":"#434343","error":"#f44336","grades":"#8bc34a","highlight":"rgba(184, 134, 11, 0.2)","input":"#40444b","primary":"#36393f","secondary":"#202225"},"options":{"borderRadius":5,"borderSize":1,"padding":10},"text":{"contrast":"#eeeeee","muted":"#72767d","primary":"#dcddde"}}},"logo":{"preset":"schoology_logo"},"name":"My Dark Theme","version":2}

### Expected behavior
The input box should change color based on the theme.

### Screenshots
![image](https://github.com/aopell/SchoologyPlus/assets/84212123/edb27825-acaf-47b7-8233-abc5cc263590)

### Additional context
N/A

### Platform
Google Chrome Version 111.0.5563.118 (Official Build) (64-bit)

**Comment by aopell** [comment]
Hi @TheThonos -- we have intentionally left out rich textboxes from theming because we want to make sure the user knows what other people will see when they submit a post or assignment. We believe it could be confusing because formatted text can look quite different if you have a dark or light theme
