### ISSUE TITLE
Typo in Webpack config leads to Schoology Plus failing to build

### ISSUE THREAD

**Issue by Vbbab** [aopell/SchoologyPlus#340]
### Describe the bug
Schoology Plus (tested at tag `v10.1.0`, 13fe8ea) currently fails to build due to a typo related to the `izitoast` module in `webpack.config.js`.

Specifically, this line in the file corresponds to the iziToast CSS entrypoint:
https://github.com/aopell/SchoologyPlus/blob/13fe8ea344d6e12ddd6c2398826f8591360bb02e/webpack.config.js#L29

The issue with this is that (at least on my system), iziToast actually gets installed to `../node_modules/izitoast` (all lowercase module name), which matches the entry in `package.json` as well. Thus, this causes an error when building since the CSS file for iziToast cannot be found.

Honestly, I am *not sure* how this went unnoticed; perhaps only my environment installs the iziToast module as `izitoast`? I noticed that the version on the Chrome Web Store is already 10.1.0, so that leads me to believe that this version must have built successfully before somehow.

This issue happens with both debug and production builds.

### Steps to reproduce
Checkout `v10.1.0`. Run `npm install && npm run build`.

### Expected behavior
Dependencies are installed; then, the extension is built successfully.

### Log from Webpack
```
ERROR in lib/izitoast
Module not found: Error: Can't resolve '/path/to/schoologyplus/node_modules/iziToast/dist/css/iziToast.min.css' in '/path/to/schoologyplus'
```

If this is confirmed to be a typo (it currently remains unchanged in the `develop` branch), I can just make a quick PR to fix it. However, I'm mainly just wondering if there's some other things at play here.

**Comment by aopell** [comment]
Thank you @Vbbab, this was because I was primarily developing on windows which doesn't care about case sensitivity in file paths. When trying to build on a new laptop in WSL I could reproduce the issue.
