### ISSUE TITLE
Add proper icons interface to theme editor

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#52]
Currently the theme editor does not have a nice UI for icon editing. It would be nice to add one. Probably just as a key (regex)/value (URL) two-column table. Potential components and conerns:

- How would icons be previewed?
- How would default icons be thoroughly previewed?
- Would there be a nice way to view default icons?

**Comment by aopell** [comment]
We might want to address the idea of viewing default icons, but I think that's not of the utmost importance since the preview option exists
