### ISSUE TITLE
Desktop notifications don't work on Firefox

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#54]
It seems to be an issue with Firefox not supporting event pages. The background page loads when the extension is first installed/updated but appears to unload afterward. The alarm event doesn't fire.

**Comment by aopell** [comment]
It most likely has something to do with when the event is registered, but I'm not sure when the correct time to register the event is

**Comment by glen3b** [comment]
- That's what I thought too (in regards to my research), but it was in the Schoology Plus background page debug interface. Strange, and the fact that it only showed up in my personal (i.e. highly confounding) environment is strange.
- This is the most promising venue of investigation. Even from Chrome docs, though, I didn't find a clear example of where to register an alarm in the simple case. Do you have a page which describes it? I'll look into this further.
- I don't think it was hitting the last callback when I stepped through, but that URL does indeed return JSON - I was mistaken. I'll try to figure out why I wasn't seeing the callback getting hit.

**Comment by glen3b** [comment]
It appears to have been related to the timing and frequency of alarm registration.
