### ISSUE TITLE
Add a way to run some JS the first time a user opens Schoology after the installation of a specific version 

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#55]

**Comment by glen3b** [comment]
Specific versions as in what?
(broadcast displays if: user version is...)
1. `<=` [future version]
2. `<=` [already published version]
3. `>=` [future version]
4. `>=` [already published version]

Although my understanding of the broadcast system is limited, I think doability is as follows:

1. Trivial: add a new field ignored by older versions, by the time the cutoff version is hit the field will be properly acknowledged.
2. Very difficult to impossible: We'd need a way to check version within the broadcast after it's processed by the broadcasting system. Possibly doable in an extremely hacky manner by putting JavaScript in the HTML broadcast, but I don't think without breaking notifications.
3. Doable, but annoying: I think we'd effectively need a second channel that isn't checked by current versions for broadcasts of this nature, or hacks similar to (2).
4. Very difficult to impossible for the same reasons as (2).
