### ISSUE TITLE
UX fixes to theme editor

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#64]
- [ ] More clearly visually indicate that the text entries for custom icons exist (they can't be seen clearly)
- [x] More clearly indicate, visually, when JSON textbox is readonly
- [x] Fix JSON textbox label in nonedit mode (it currently reads "Paste to import theme" but is readonly)
- [x] More clearly indicate that class name patterns are regular expressions

**Comment by aopell** [comment]
Closed in 851194b3eed6607670e6cc123f821080f4816aa9
