### ISSUE TITLE
Allow custom themes to use rainbow

### ISSUE THREAD

**Issue by penguinee232** [aopell/SchoologyPlus#66]
It is currently impossible to create a custom theme with rainbow coloration.

**Comment by glen3b** [comment]
When we add rainbowing as a component to custom themes in the theme editor I'd like to propose adding some of the following tweakable parameters:
- A base saturation-lightness scalar, as proposed in #53 
- Speed of rainbow cycling
More wishlist-type features which are more complicated, and quite possibly out of scope, but which I would like to at least look at:
- More arbitrary paths within the color circle, i.e. not fixing paths to be concentric circles with the color wheel
![Color wheel](https://banner2.kisspng.com/20180405/hyw/kisspng-color-wheel-hsl-and-hsv-barvni-model-hsl-color-the-colours-5ac6d43b0088f4.2841005915229798990022.jpg)
This would allow e.g. a rainbow within the green range
- Noncontinuous paths: smear between various checkpoint colors, so I can have a theme cycling between (e.g.) yellow and purple, with little in between, but without choppy jumps

**Comment by aopell** [comment]
This would require some changes to how themes work, but is a good idea

**Comment by aopell** [comment]
There exists functionality for themes to run functions every 100ms, so we can add a few ways for custom themes to hook into this. Rainbow is a good start.
