### ISSUE TITLE
Replace theme spec sheet with comprehensive theme editor help page

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#68]
Should discuss how all aspects of the theme editor work and include the theme spec

It should also include more theme examples

It should be linked from the theme editor for easy access

**Comment by glen3b** [comment]
My take on what content it should include:
- [ ] Existing JSON theme spec (probably at the bottom)
- [ ] Potentially write it such that it's collapsible, i.e. shorter if you know what you're looking for
- [ ] Retaken animated screen capture of how to get to the theme editor
- [ ] Brief overview of setting the various obvious settings (with perhaps more detail for the RGB color settings)
- [ ] Overview on management: deletion, creation, theme application, etc
- [ ] Detailed section on icons
- [ ] Importing and exporting

Also worth considering: another possibility for documentation is something like a video tutorial. Personally I'm not a huge fan when I know what I'm looking for, but for basics of usage it might be a good idea, or as a complement to text documentation.

**Comment by aopell** [comment]
Done, see wiki
