### ISSUE TITLE
Discussion: Remove broadcasts entirely?

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#76]
Broadcasts have a lot of problems, and may no longer serve a purpose at all after recent additions:

1. Broadcasts are hardly ever used
    1. Since their creation, broadcasts have been used only 3 times
2. They are extremely unsafe
    1. Arbitrary and potentially dangerous HTML and JavaScript can be embedded into the page through broadcasts
3. After the addition of code running on first launch of a new version, they seem to be unnecessary
    1. At what point do we need to send a message to all users so urgently that we couldn't just push a minor update with the message?
    2. For example, see the current 4.2 first run code which creates an unread broadcast which simply shows the broadcast in the news feed (if the user has that setting enabled) as well as a popup notification

Just a point of discussion, but I feel like broadcasts no longer serve a purpose at this point.
I'm interested in your feedback @glen3b

**Comment by glen3b** [comment]
If we're referring just to the push-via-internet capability of broadcasts (not the in-newsfeed display, which you use in your example 4.2 first run code), that can probably be removed, especially considering point 2. Minor updates can do a lot in most cases.

The one potential case where the existing system could help would be if we transition update backends or need to reach users who are having issues updating for whatever reason, and I know we did that once. However I don't think that case alone justifies the system as we have it now.

**Comment by aopell** [comment]
Ok, so I'm going to remove that functionality. After this I think we should put a feature freeze on 4.2 and determine whether it should be called 4.2 or not. The only thing remaining before a vNext release is some theme editor documentation, which I'm currently working on.
