### ISSUE TITLE
Reform build system

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#81]
When this project started fairly simplistically, it didn't have any dependencies or the like. But now, we bundle various libraries and have more complicated source code. In particular for the issue of many libraries, is it worth replacing our existing zip-and-sign build system with a more complicated one with more proper dependency management? (Discussion)

**Comment by aopell** [comment]
I think it's probably a good idea, yeah. I'm not sure exactly what we'd want though.
