### ISSUE TITLE
Clarify nonofficial status

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#86]
In promotional material, the README, and related documents, we should make sure that we are being very explicit about the fact that we are not affiliated with Schoology.

**Comment by aopell** [comment]
The following text has been added to the README, Chrome Web Store description, and Contributors modal:

```
Schoology Plus is not affiliated with Schoology Inc. or the Los Angeles Unified School District. Schoology, the SCHOOLOGY® wordmark, and the S logo are registered and unregistered trademarks of Schoology, Inc. in the United States. All product names, logos, and brands are property of their respective owners.
```
