### ISSUE TITLE
Add support for new interface

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#95]
LAUSD Schoology is updating the interface on Dec 15.
We will need to make changes to support this.

- [x] Theming (color) logic for new titlebar and footer and such
- [x] Schoology Plus settings button
- [x] All courses dropdown tweaks
- [x] Custom icon related code (size change?)
- [x] Big Schoology/LAUSD/custom icon logic/replacement
- [x] Code hooking notifications dropdown and related (potentially)

**Comment by aopell** [comment]
Also necessary as a part of this: push a minor version next week stating that Schoology Plus may temporarily be broken when Schoology is updated.

**Comment by aopell** [comment]
Previous comment addressed in version 4.3.2

**Comment by glen3b** [comment]
In so doing this, I'd like to propose we don't strip support for the old interface.
Other deployments, like those we might support via #82, might still be using it; additionally, that will ensure this doesn't break during development.

**Comment by aopell** [comment]
Though I agree with this in principle it will be very difficult to test in the future if we add new interface features. We would have no idea how new additions would appear or if they would outright break support for the old interface. I think it would be too much trouble.

**Comment by aopell** [comment]
See https://github.com/aopell/SchoologyPlus/projects/4 for progress
