### ISSUE TITLE
Update documentation to reflect new interface

### ISSUE THREAD

**Issue by glen3b** [aopell/SchoologyPlus#97]
We should update our docs (screenshots in particular) to reflect changes made in the new Schoology interface (deployed in LAUSD on Dec 15) and resulting Schoology Plus changes.

**Comment by glen3b** [comment]
README images:
- [ ] "Blue Theme" titlebar
- [ ] Custom Themes UI
- [ ] Course Icons in courses dropdown
- [ ] Theme Editor main UI
- [ ] (Possibly Schoology Plus settings, if it's been updated)

Wiki:
- [ ] Every similar image on the wiki's Features page

Worth noting - it looks like the wiki page and the readme are duplicated. How should we handle this?

**Comment by aopell** [comment]
In addition:

- [ ] Update theme docs for new rainbow support

**Comment by aopell** [comment]
See wiki branch `version-5.1` which should be merged to `master` with the release of v5.1

**Comment by aopell** [comment]
Also, missing from README:
- [ ] Courses in Common
